const work_exp = [
    {
        role: 'Software Developer Intern',
        company: 'Avena Tech Corporation',
        bullets: [
            'Redesigned websites in Figma and developed them in React.js and Tailwind.css improving load times by 75%',
            'Developed and integrated REST API endpoints using Express.js and MongoDB, successfully migrating over 60 Wordpress blogs to a new, efficient platform for future blogs',
            'Successfully diagnosed and resolved complex issues with WordPress websites, including troubleshooting plugin conflicts, database connectivity problems, and server-related issues to improve load times',
            'Coordinated 8 client meetings to discuss requirements and design changes, ensuring alignment with client needs and adherence to Nielsen Norman Group’s UX/UI principles'
        ],
        date: 'Jul 2023 - Present'
    },
    {
        role: 'Research Assistant',
        company: 'Simon Fraser Univserity',
        bullets: [
            'Developed Unity simulations in C# for IMU sensor data in order to analyze whether it accurately matches the real world, allowing researchers to see how good their machine learning models are',
            'Collected XYZ and rotational data generated from training data generated by the T2M-GPT model in order for researchers to identify joints of motion to increase accuracy to real human motion',
            'Collaborated with graduate students from SFU and Darthmouth College under the supervision of Dr. Xing-Dong Yang'
        ],
        date: 'Jun 2023 - Sept 2023'
    },
    {
        role: 'Technical Support',
        company: 'Auphan Software',
        bullets: [
            'Resolved 1000+ tickets for POS software systems, payment processor integration, and software installation with big North American companies',
            'Collaborated with sales, development, and technical support teams to communicate regression reports and ensured tracking and support until resolution',
            'Troubleshooted database and server outages involving Apache, PostgreSQL, and pgbouncer',
        ],
        date: 'Mar 2021 - Aug 2021'
    }
]


const Experience = () => {
    return (
        <section id='experience' className='flex flex-col items-center bg-black text-white '>
            <div className='mx-12 md:mx-24 w-[80%]'>
                <hr className='p-12 mt-12' />
                <h1 className='font-extralight text-4xl mb-12'>EXPERIENCE</h1>
                <div className='flex flex-col gap-14'>
                    {
                        work_exp.map((work, index) => {
                            return (
                                <div key={index} className='flex flex-col gap-4'>
                                    <div className='flex justify-between items-center'>
                                        <h2 className='text-lg md:text-2xl'>{work.role}</h2>
                                        <h3 className='text-sm md:text-lg'>{work.date}</h3>
                                    </div>
                                    <h3 className='text-blue-500'>{work.company}</h3>
                                    <ul className='list-disc pl-5'>
                                        {
                                            work.bullets.map((bullet, index) => {
                                                return (
                                                    <li key={index} className='mb-1'>{bullet}</li>
                                                )
                                            })
                                        }
                                    </ul>
                                </div>
                            )
                        }
                    )}
                </div>
            </div>
        </section>
    );
}
export default Experience;